export const dict = {
  en: {
    nav: ['About', 'Nominations', 'Program', 'Partners', 'FAQ'],
    heroKicker: 'Sep 20, 2026 · Garage Mall, Yerevan',
    heroDate: 'September 20, 2026',
    heroSub:
      "Armenia’s loudest car culture event returns. 11 nominations, hundreds of builds, one all-out day at Garage Mall.",
    cta1: 'Register Your Car',
    cta2: 'Become a Partner',
    secAbout: 'About the show',
    aboutHead: 'One Day. Full Throttle.',
    aboutText:
      "Tuning Show brings Armenia’s car-building scene together at Garage Mall — retro, JDM, off-road, muscle, custom and more. Judged live across 11 nominations, in front of thousands of visitors. Free entry for everyone.",
    secCount: 'Countdown to show day',
    secNoms: 'Nominations',
    nomsHead: '11 Ways To Win',
    nomsSub: 'An independent jury scores every entry live on show day.',
    secProgram: 'Program',
    programHead: 'Show day, hour by hour',
    scheduleNote: 'schedule placeholder — final times TBC',
    secApply: 'Register',
    applyHead: 'Enter Your Build',
    tabParticipant: 'Participant',
    tabVisitor: 'Visitor',
    tabPartner: 'Partner',
    visitorIntro:
      'Coming as a guest? Register so we know how many to expect — it takes a minute and helps us plan the day.',
    fCity: 'City',
    fParty: 'How many are coming with you?',
    fOccupation: 'Occupation',
    fHear: 'How did you hear about Tuning Show?',
    fInterest: 'What are you most interested in?',
    selectPlaceholder: 'Select one or more…',
    fVisited: 'Have you been to Garage Mall before?',
    fConsent:
      'I agree that my data may be used by Garage Mall and Tuning Show to organize participation and to send updates about the event and future offers.',
    partnerLeadHead: 'Your brand can be at the heart of Tuning Show',
    partnerLeadSub:
      'Join the event and build a presence people won’t just see — they’ll remember.',
    partnerWhyHead: 'Why partner with Tuning Show',
    partnerWhy: [
      '5,000+ active visitors in a single day',
      'Direct contact with your target audience',
      'Brand visibility across the event space',
    ],
    partnerHowHead: 'How to become a partner',
    partnerHowText:
      'Fill out the application below and tell us how you’d like to collaborate. Our team will get in touch to discuss your goals, walk you through partnership options and put together a tailored offer.',
    fContact: 'Contact person',
    fPosition: 'Position',
    fWebsite: 'Website or social page',
    fPartnerIdea: 'Your idea or expectations',
    fPartnerDeck: 'Attach company presentation',
    fPartnerDeckHint: 'PDF, PPT or PPTX',
    fSubmitPartner: 'Send partnership application',
    thanksPartner: 'Thank you for your interest',
    thanksPartnerSub:
      'Your partnership application has been sent. Our team will review the details and get in touch to discuss the collaboration.',
    secTerms: 'Terms',
    termsHead: 'Terms of participation & consent',
    termsIntro: 'I confirm that:',
    termsList: [
      'I will follow all organizer instructions and safety rules,',
      'I understand that in case of late arrival the organizers may deny the vehicle entry,',
      'throughout the event I, or a person authorized by me, will stay near the vehicle,',
      'I will not leave the event area before the set closing time without the organizers’ consent,',
      'I will present the vehicle clean, undamaged and ready for display,',
      'without the organizers’ permission, burnout, drifting, high-speed driving or other dangerous actions are prohibited,',
      'without the organizers’ permission, playing loud music or using a sound system is prohibited,',
      'I will not place advertising materials, flags or other banners next to the vehicle without the organizers’ permission,',
      'I understand that the jury’s decisions are final and not subject to appeal,',
      'I understand that the organizers are not liable for damage, loss or theft of the vehicle or personal property.',
    ],
    fTerms: 'I have read and agree to the terms of participation',
    fTermsLink: '(read)',
    noticeHead: 'Before you apply',
    noticeBody:
      "Submitting this form does not guarantee confirmed participation — our team will contact confirmed entrants directly. Participation fee: 20,000 AMD for cars, 10,000 AMD for motorcycles, charged only after confirmation. Non-refundable.",
    fName: 'Full Name',
    fPhone: 'Phone Number',
    fAge: 'Age',
    fEmail: 'Email',
    optional: 'optional',
    fMake: 'Vehicle Make',
    fModel: 'Vehicle Model',
    fYear: 'Year of Manufacture',
    fPlate: 'License Plate',
    fNom: 'Choose Nomination',
    fUpload: 'Upload Photos',
    fUploadCta: 'Click or drop photos here',
    fUploadHint: 'All angles + interior, JPG or PNG',
    fCompany: 'Company Name',
    fMsg: 'Message',
    fSubmit: 'Send Application',
    submitting: 'Sending…',
    formError: 'Something went wrong. Please try again.',
    formNotConfigured: 'Submissions are not connected yet. Please try again later.',
    thanks: 'Application received',
    thanksSub:
      "This doesn’t confirm your spot yet — we’ll contact you directly once it’s reviewed.",
    secPartners: 'Partners',
    partnersHead: 'Built with our partners',
    titleSponsor: 'Title sponsor',
    titleSponsorPlaceholder: 'YOUR LOGO',
    partnerCta: 'Become a Partner',
    secLocation: 'Location',
    locAddress: 'Garage Mall, Yerevan, Armenia',
    locParking: 'Free on-site parking for visitors',
    locHours: 'Doors 15:00 — 23:00',
    locFree: 'Free entry for all visitors',
    locDirections: 'Open in Maps',
    mapNote: 'embed Garage Mall map',
    secFaq: 'FAQ',
    faqHead: 'Good to know',
    footTag: "Armenia’s automotive tuning culture event.",
    footContact: 'Contact',
    footFollow: 'Follow',
    footPrivacy: 'Privacy Policy',
  },
  ru: {
    nav: ['О шоу', 'Номинации', 'Программа', 'Партнёры', 'Вопросы'],
    heroKicker: '20 сентября 2026 · Garage Mall, Ереван',
    heroDate: '20 сентября 2026',
    heroSub:
      'Самое громкое автособытие Армении возвращается. 11 номинаций, сотни проектов, один безудержный день в Garage Mall.',
    cta1: 'Записать авто',
    cta2: 'Стать партнёром',
    secAbout: 'О шоу',
    aboutHead: 'Один день. Полный газ.',
    aboutText:
      'Собираем автостроительное сообщество Армении в Garage Mall — ретро, JDM, off-road, масл-кар, кастом и многое другое. Живое судейство в 11 номинациях перед тысячами гостей. Вход свободный для всех.',
    secCount: 'До начала шоу',
    secNoms: 'Номинации',
    nomsHead: '11 способов победить',
    nomsSub: 'Независимое жюри оценивает каждый автомобиль вживую в день шоу.',
    secProgram: 'Программа',
    programHead: 'День шоу по часам',
    scheduleNote: 'предварительное расписание — время уточняется',
    secApply: 'Регистрация',
    applyHead: 'Заяви свой автомобиль',
    tabParticipant: 'Участник',
    tabVisitor: 'Посетитель',
    tabPartner: 'Партнёр',
    visitorIntro:
      'Придёте как гость? Зарегистрируйтесь, чтобы мы понимали, сколько ждать людей — это займёт минуту и поможет нам спланировать день.',
    fCity: 'Город',
    fParty: 'Сколько человек вас будет?',
    fOccupation: 'Род занятий',
    fHear: 'Откуда узнали о Tuning Show?',
    fInterest: 'Что вам интереснее всего?',
    selectPlaceholder: 'Выберите одно или несколько…',
    fVisited: 'Бывали ли вы раньше в Garage Mall?',
    fConsent:
      'Согласен(на), что мои данные могут использоваться Garage Mall и Tuning Show для организации участия и отправки информации о мероприятии и будущих предложениях.',
    partnerLeadHead: 'Ваш бренд может оказаться в центре Tuning Show',
    partnerLeadSub:
      'Присоединяйтесь к событию и создайте присутствие, которое не только увидят, но и запомнят.',
    partnerWhyHead: 'Почему стоит стать партнёром',
    partnerWhy: [
      '5 000+ активных посетителей за один день',
      'Прямой контакт с целевой аудиторией',
      'Видимость бренда на площадке события',
    ],
    partnerHowHead: 'Как стать партнёром',
    partnerHowText:
      'Заполните заявку ниже и укажите, в каком формате хотите сотрудничать. Наша команда свяжется с вами, чтобы обсудить цели, показать возможности партнёрства и подготовить индивидуальное предложение.',
    fContact: 'Контактное лицо',
    fPosition: 'Должность',
    fWebsite: 'Сайт или соцсеть',
    fPartnerIdea: 'Ваша идея или ожидания',
    fPartnerDeck: 'Прикрепите презентацию компании',
    fPartnerDeckHint: 'PDF, PPT или PPTX',
    fSubmitPartner: 'Отправить заявку на партнёрство',
    thanksPartner: 'Спасибо за интерес',
    thanksPartnerSub:
      'Ваша заявка на партнёрство отправлена. Наша команда изучит детали и свяжется с вами для обсуждения сотрудничества.',
    secTerms: 'Условия',
    termsHead: 'Условия участия и согласие',
    termsIntro: 'Подтверждаю, что:',
    termsList: [
      'соблюдаю все указания организаторов и правила безопасности,',
      'осведомлён(а), что при опоздании организаторы могут отказать во въезде автомобиля,',
      'в течение всего мероприятия я или уполномоченное мной лицо будет находиться рядом с автомобилем,',
      'без согласия организаторов не покину территорию мероприятия до установленного времени завершения,',
      'предоставлю автомобиль в чистом, неповреждённом и готовом к показу виде,',
      'без разрешения организаторов запрещены burnout, drifting, езда на высокой скорости и другие опасные действия,',
      'без разрешения организаторов запрещено включать громкую музыку или использовать звуковую систему,',
      'не размещу рядом с автомобилем рекламные материалы, флаги или иные баннеры без разрешения организаторов,',
      'осведомлён(а), что решения жюри окончательны и обжалованию не подлежат,',
      'осведомлён(а), что организаторы не несут ответственности за повреждение, потерю или кражу автомобиля или личного имущества.',
    ],
    fTerms: 'Я ознакомился(лась) и согласен(на) с условиями участия',
    fTermsLink: '(читать)',
    noticeHead: 'Перед подачей заявки',
    noticeBody:
      'Заполнение формы не означает автоматическое подтверждение участия — наша команда свяжется с подтверждёнными участниками напрямую. Взнос за участие: 20 000 драм для автомобилей, 10 000 драм для мотоциклов, списывается только после подтверждения. Не возвращается.',
    fName: 'Имя, Фамилия',
    fPhone: 'Номер телефона',
    fAge: 'Возраст',
    fEmail: 'Email',
    optional: 'необязательно',
    fMake: 'Марка автомобиля',
    fModel: 'Модель',
    fYear: 'Год выпуска',
    fPlate: 'Гос. номер',
    fNom: 'Выберите номинацию',
    fUpload: 'Загрузите фото',
    fUploadCta: 'Нажмите или перетащите фото сюда',
    fUploadHint: 'Все ракурсы + салон, JPG или PNG',
    fCompany: 'Название компании',
    fMsg: 'Сообщение',
    fSubmit: 'Отправить заявку',
    submitting: 'Отправка…',
    formError: 'Что-то пошло не так. Попробуйте ещё раз.',
    formNotConfigured: 'Приём заявок пока не подключён. Попробуйте позже.',
    thanks: 'Заявка принята',
    thanksSub: 'Это ещё не подтверждает участие — мы свяжемся с вами напрямую после рассмотрения.',
    secPartners: 'Партнёры',
    partnersHead: 'Сделано с партнёрами',
    titleSponsor: 'Главный спонсор',
    titleSponsorPlaceholder: 'ВАШ ЛОГОТИП',
    partnerCta: 'Стать партнёром',
    secLocation: 'Локация',
    locAddress: 'Garage Mall, Ереван, Армения',
    locParking: 'Бесплатная парковка для гостей',
    locHours: 'Двери 15:00 — 23:00',
    locFree: 'Вход свободный для всех гостей',
    locDirections: 'Открыть на карте',
    mapNote: 'здесь будет карта Garage Mall',
    secFaq: 'Вопросы',
    faqHead: 'Важно знать',
    footTag: 'Событие автотюнинговой культуры Армении.',
    footContact: 'Контакты',
    footFollow: 'Мы в соцсетях',
    footPrivacy: 'Политика конфиденциальности',
  },
  am: {
    nav: ['Մեր մասին', 'Անվանակարգեր', 'Ծրագիր', 'Գործընկերներ', 'Հարցեր'],
    heroKicker: '20 սեպտեմբերի, 2026 · Garage Mall, Երևան',
    heroDate: '20 սեպտեմբերի, 2026',
    heroSub:
      'Հայաստանի ամենաաղմկոտ ավտոմշակութային իրադարձությունը վերադառնում է: 11 անվանակարգ, հարյուրավոր նախագծեր, մեկ անմոռանալի օր Garage Mall-ում:',
    cta1: 'Գրանցի՛ր մեքենադ',
    cta2: 'Դառնալ գործընկեր',
    secAbout: 'Մեր մասին',
    aboutHead: 'Մեկ օր՝ առավելագույն հզորությամբ',
    aboutText:
      'Tuning Show-ն մեկ հարթակում կհամախմբի Հայաստանի ավտոմոբիլային մշակույթի ամենատպավորիչ ներկայացուցիչներին՝ ռետրո, JDM, արտաճանապարհային, Muscle Car, անհատական նախագծեր և բազմաթիվ այլ բացառիկ մեքենաներ։ Մասնակիցները կմրցեն 11 անվանակարգերում և կգնահատվեն անկախ ժյուրիի կողմից՝ հազարավոր այցելուների ներկայությամբ։ Այցելուների մուտքն անվճար է։',
    secCount: 'Մինչև Tuning Show-ի մեկնարկը մնաց՝',
    secNoms: 'Անվանակարգեր',
    nomsHead: '11 անվանակարգ՝ լավագույնը դառնալու համար',
    nomsSub: 'Միջոցառման օրը անկախ և մասնագիտացված ժյուրին տեղում կգնահատի յուրաքանչյուր մասնակցի մեքենան։',
    secProgram: 'Ծրագիր',
    programHead: 'Միջոցառման ծրագիր',
    scheduleNote: 'Ներկայացված ժամանակացույցը նախնական է։ Վերջնական ժամերը կարող են փոփոխվել։',
    secApply: 'Գրանցվի՛ր որպես',
    applyHead: 'Ներկայացրու քո մեքենան Tuning Show-ում',
    tabParticipant: 'Մասնակից',
    tabVisitor: 'Այցելու',
    tabPartner: 'Գործընկեր',
    visitorIntro:
      'Գալի՞ս եք որպես հյուր: Գրանցվեք, որ իմանանք՝ մոտավորապես քանի մարդ ենք սպասում — սա կխնայի ընդամենը մեկ րոպե և կօգնի մեզ պլանավորել օրը:',
    fCity: 'Քաղաք',
    fParty: 'Քանի՞ հոգով եք գալու',
    fOccupation: 'Զբաղմունք',
    fHear: 'Որտեղի՞ց եք իմացել Tuning Show-ի մասին',
    fInterest: 'Ի՞նչն է Ձեզ ամենաշատը հետաքրքրում',
    selectPlaceholder: 'Ընտրեք մեկ կամ մի քանիսը…',
    fVisited: 'Նախկինում այցելե՞լ եք Garage Mall',
    fConsent:
      'Համաձայն եմ, որ իմ տվյալները կարող են օգտագործվել Garage Mall-ի և Tuning Show-ի կողմից մասնակցությունը կազմակերպելու և միջոցառման ու հետագա առաջարկների մասին տեղեկություններ ուղարկելու համար:',
    partnerLeadHead: 'Ձեր բրենդը կարող է լինել Tuning Show-ի կենտրոնում',
    partnerLeadSub:
      'Միացեք միջոցառմանը և ստեղծեք ներկայություն, որը ոչ միայն կտեսնեն, այլև կհիշեն:',
    partnerWhyHead: 'Ինչո՞ւ դառնալ Tuning Show-ի գործընկեր',
    partnerWhy: [
      '5,000+ ակտիվ այցելու մեկ օրում',
      'Ուղիղ շփում թիրախային լսարանի հետ',
      'Բրենդի տեսանելիություն միջոցառման տարածքում',
    ],
    partnerHowHead: 'Ինչպե՞ս դառնալ գործընկեր',
    partnerHowText:
      'Լրացրեք ստորև ներկայացված հայտը և նշեք, թե ինչ ձևաչափով եք ցանկանում համագործակցել: Մեր թիմը կկապվի Ձեզ հետ՝ քննարկելու Ձեր նպատակները, ներկայացնելու գործընկերության հնարավորությունները և կազմելու անհատական առաջարկ:',
    fContact: 'Կոնտակտային անձ',
    fPosition: 'Պաշտոն',
    fWebsite: 'Կայք կամ սոցիալական էջ',
    fPartnerIdea: 'Ձեր գաղափարը կամ ակնկալիքները',
    fPartnerDeck: 'Կցեք ընկերության ներկայացումը',
    fPartnerDeckHint: 'PDF, PPT կամ PPTX',
    fSubmitPartner: 'Ուղարկել գործընկերության հայտը',
    thanksPartner: 'Շնորհակալություն հետաքրքրվածության համար',
    thanksPartnerSub:
      'Ձեր գործընկերության հայտը հաջողությամբ ուղարկվել է: Մեր թիմը կուսումնասիրի տրամադրված տեղեկությունները և կապ կհաստատի Ձեզ հետ՝ համագործակցությունը մանրամասն քննարկելու համար:',
    secTerms: 'Պայմաններ',
    termsHead: 'Մասնակցության պայմաններ և համաձայնություն',
    termsIntro: 'Հաստատում եմ, որ`',
    termsList: [
      'կպահպանեմ կազմակերպիչների բոլոր ցուցումները և անվտանգության կանոնները,',
      'տեղեկացված եմ, որ ուշ ժամանելու դեպքում կազմակերպիչները կարող են մերժել մեքենայի մուտքը,',
      'միջոցառման ողջ ընթացքում ես կամ իմ կողմից լիազորված անձը կգտնվի մեքենայի մոտ,',
      'առանց կազմակերպիչների համաձայնության չեմ լքի միջոցառման տարածքը մինչև սահմանված ավարտը,',
      'կներկայացնեմ մեքենան մաքուր, անվնաս և ցուցադրության համար պատրաստ վիճակում,',
      'առանց կազմակերպիչների թույլտվության արգելված է՝ burnout, drifting, բարձր արագությամբ երթևեկություն կամ այլ վտանգավոր գործողություններ,',
      'առանց կազմակերպիչների թույլտվության արգելված է՝ բարձր ձայնով երաժշտություն կամ ձայնային համակարգ օգտագործելը,',
      'մեքենայի կողքին չեմ տեղադրի գովազդային նյութեր, դրոշներ կամ այլ պաստառներ առանց կազմակերպիչների թույլտվության,',
      'տեղեկացված եմ, որ ժյուրիի որոշումները վերջնական են և բողոքարկման ենթակա չեն,',
      'տեղեկացված եմ, որ կազմակերպիչները պատասխանատվություն չեն կրում մեքենայի կամ անձնական գույքի վնասման, կորստի կամ գողության համար:',
    ],
    fTerms: 'Ծանոթացել եմ մասնակցության պայմաններին և համաձայն եմ',
    fTermsLink: '(կարդալ)',
    noticeHead: 'Մինչ հայտագրվելը',
    noticeBody:
      'Հայտի լրացումը դեռևս չի նշանակում մասնակցության ավտոմատ հաստատում։ Բոլոր հայտերը կենթարկվեն նախնական ընտրության, և կազմակերպիչները կապ կհաստատեն միայն հաստատված մասնակիցների հետ։ Մասնակցության վճարը կազմում է՝ մեքենաների համար՝ 20 000 ՀՀ դրամ, մոտոցիկլետների համար՝ 10 000 ՀՀ դրամ։ Վճարումը կատարվում է միայն մասնակցության հաստատումից հետո։ Մասնակցության վճարը վերադարձման ենթակա չէ։',
    fName: 'Անուն, Ազգանուն',
    fPhone: 'Հեռախոսահամար',
    fAge: 'Տարիք',
    fEmail: 'Email',
    optional: 'ոչ պարտադիր',
    fMake: 'Մակնիշ',
    fModel: 'Մոդել',
    fYear: 'Արտադրության տարեթիվ',
    fPlate: 'Պետհամարանիշ',
    fNom: 'Ընտրե՛ք անվանակարգը',
    fUpload: 'Վերբեռնե՛ք լուսանկարները',
    fUploadCta: 'Վերբեռնե՛ք լուսանկարները այստեղ',
    fUploadHint: 'Պարտադիր է կցել մեքենայի լուսանկարները բոլոր կողմերից, ինչպես նաև սրահի լուսանկարները։ Ընդունելի ձևաչափեր՝ JPG կամ PNG',
    fCompany: 'Ընկերության անուն',
    fMsg: 'Հաղորդագրություն',
    fSubmit: 'Ուղարկել հայտը',
    submitting: 'Ուղարկվում է…',
    formError: 'Ինչ-որ բան սխալ գնաց: Փորձեք նորից:',
    formNotConfigured: 'Հայտերի ընդունումը դեռ միացված չէ: Փորձեք ավելի ուշ:',
    thanks: 'Հայտը ստացված է',
    thanksSub:
      'Հայտի ուղարկումը դեռևս չի նշանակում մասնակցության հաստատում։ Մեր թիմը կուսումնասիրի ներկայացված տվյալները և հաստատման դեպքում կապ կհաստատի Ձեզ հետ։',
    secPartners: 'Գործընկերներ',
    partnersHead: 'Հովանավորներ',
    titleSponsor: 'Գլխավոր հովանավոր',
    titleSponsorPlaceholder: 'ՁԵՐ ՆՇԱՆԸ',
    partnerCta: 'Դառնալ գործընկեր',
    secLocation: 'Վայր',
    locAddress: 'Garage Mall, Երևան, Հայաստան',
    locParking: 'Անվճար կայանատեղի',
    locHours: 'Միջոցառման ժամերը՝ 15:00–23:00',
    locFree: 'Այցելուների մուտքն ազատ է։',
    locDirections: 'Բացել քարտեզում',
    mapNote: 'այստեղ կլինի Garage Mall-ի քարտեզը',
    secFaq: 'Հարցեր',
    faqHead: 'Հաճախ տրվող հարցեր',
    footTag: 'Հայաստանի ավտոտյունինգի մշակութային իրադարձությունը:',
    footContact: 'Կապ',
    footFollow: 'Հետևեք մեզ',
    footPrivacy: 'Գաղտնիության քաղաքականություն',
  },
};

export const countdownLabels = {
  en: ['Days', 'Hours', 'Min', 'Sec'],
  ru: ['Дни', 'Часы', 'Мин', 'Сек'],
  am: ['Օր', 'Ժամ', 'Րոպե', 'Վայրկ'],
};

export const statVals = ['100+', '11', '5,000+', '8,000 m²'];

export const statLabels = {
  en: ['Builds & projects', 'Nominations', 'Expected visitors', 'Exhibition area'],
  ru: ['Проектов', 'Номинаций', 'Посетителей', 'Площадь'],
  am: ['Մեքենա', 'Անվանակարգ', 'Այցելու', 'Տարածք'],
};

export const nominations = [
  { en: 'Best Retro Car (up to 1959)', ru: 'Лучший ретроавтомобиль (до 1959 г.)', am: 'Լավագույն ռետրո մեքենա (մինչև 1959 թ.)' },
  { en: 'Best Retro Car (1960–1980)', ru: 'Лучший ретроавтомобиль (1960–1980)', am: 'Լավագույն ռետրո մեքենա (1960–1980 թթ.)' },
  { en: 'Best Historic Japan / JDM', ru: 'Лучший Historic Japan / JDM', am: 'Լավագույն Historic Japan / JDM' },
  { en: 'Best Off-Road (Camping Build)', ru: 'Лучший off-road (Camping Build)', am: 'Լավագույն օֆ-ռոդ մեքենա (Camping Build)' },
  { en: 'Best Off-Road (Sport Build)', ru: 'Лучший off-road (Sport Build)', am: 'Լավագույն օֆ-ռոդ մեքենա (Sport Build)' },
  { en: 'Best Off-Road (Best Tuned)', ru: 'Лучший off-road (Best Tuned Off-Road)', am: 'Լավագույն օֆ-ռոդ մեքենա (Best Tuned Off-Road)' },
  { en: 'Best Exterior', ru: 'Лучший экстерьер', am: 'Լավագույն արտաքին տեսք' },
  { en: 'Best Motorcycle (Chopper / Cruiser / Sport)', ru: 'Лучший мотоцикл (Chopper / Cruiser / Sport Bike)', am: 'Լավագույն մոտոցիկլետ (Chopper / Cruiser / Sport Bike)' },
  { en: 'Best Muscle Car', ru: 'Лучший Muscle Car', am: 'Լավագույն Muscle Car' },
  { en: 'Best Custom Build', ru: 'Лучший кастом-проект (Custom Build)', am: 'Լավագույն ինքնաշեն նախագիծ (Custom Build)' },
  { en: 'Best Sports Car', ru: 'Лучший спорткар', am: 'Լավագույն սպորտային մեքենա' },
];

export const visitorHear = {
  en: ['Instagram', 'Facebook', 'Word of mouth', 'From friends', 'Other'],
  ru: ['Instagram', 'Facebook', 'Сарафанное радио', 'От друзей', 'Другое'],
  am: ['Instagram', 'Facebook', 'Խոսակցություններից', 'Ընկերներից', 'Այլ'],
};

export const visitorInterest = {
  en: ['Tuning cars', 'Retro cars', 'Sport cars', 'Off-road cars', 'Motorcycles', 'Entertainment program', 'Food court', 'Other'],
  ru: ['Тюнинг-авто', 'Ретро-авто', 'Спорткары', 'Внедорожники', 'Мотоциклы', 'Развлекательная программа', 'Фуд-корт', 'Другое'],
  am: ['Թյունինգ մեքենաներ', 'Ռետրո մեքենաներ', 'Սպորտային մեքենաներ', 'Օֆ-ռոդ մեքենաներ', 'Մոտոցիկլետներ', 'Ժամանցային ծրագիր', 'Սննդի գոտի', 'Այլ'],
};

export const visitorVisited = {
  en: ['Yes, regularly', 'Yes, a few times', 'Yes, once', 'No, this will be my first visit'],
  ru: ['Да, регулярно', 'Да, несколько раз', 'Да, один раз', 'Нет, впервые'],
  am: ['Այո, հաճախ եմ այցելում', 'Այո, մի քանի անգամ եղել եմ', 'Այո, մեկ անգամ', 'Ոչ, սա կլինի իմ առաջին այցը'],
};

export const schedule = [
  { time: '15:00–16:00', en: { title: 'RECEPTION & WARM-UP', desc: 'Vehicles arrive and register. Participants take their assigned spots.' }, ru: { title: 'RECEPTION & WARM-UP', desc: 'Приезд и регистрация автомобилей. Участники занимают отведённые места.' }, am: { title: 'RECEPTION & WARM-UP', desc: 'Մեքենաների ժամանում և գրանցում: Մասնակիցները կայանում են նախատեսված տեղերում:' } },
  { time: '16:00–16:30', en: { title: 'OFFICIAL OPENING', desc: 'Opening ceremony. Host’s welcome. Event rules and jury introduced.' }, ru: { title: 'OFFICIAL OPENING', desc: 'Церемония открытия. Приветствие ведущего. Представление правил и жюри.' }, am: { title: 'OFFICIAL OPENING', desc: 'Բացման արարողություն: Հաղորդավարի ողջույնի խոսքը: Միջոցառման կանոնների ներկայացում: Ժյուրիի ներկայացում:' } },
  { time: '16:30–18:30', en: { title: 'ACTION SHOW', desc: 'Vehicle showcase and live jury evaluation.' }, ru: { title: 'ACTION SHOW', desc: 'Показ автомобилей и оценка жюри.' }, am: { title: 'ACTION SHOW', desc: 'Մեքենաների ցուցադրություն և ժյուրիից գնահատում:' } },
  { time: '18:30–20:00', en: { title: 'INTERACTIVE ENGAGEMENT', desc: 'DJ, music, games and contests for the audience.' }, ru: { title: 'INTERACTIVE ENGAGEMENT', desc: 'DJ, музыка, игры и конкурсы для зрителей.' }, am: { title: 'INTERACTIVE ENGAGEMENT', desc: 'DJ, երաժշտություն, խաղեր և մրցույթներ հանդիսատեսի համար:' } },
  { time: '20:30–21:00', en: { title: 'RAFFLE', desc: 'Wrap-up of the jury’s final decisions.' }, ru: { title: 'RAFFLE', desc: 'Подведение итогов финальных решений жюри.' }, am: { title: 'RAFFLE', desc: 'Ժյուրիի վերջնական որոշումների ամփոփում:' } },
  { time: '21:00–22:00', en: { title: 'GRAND PRIZE CEREMONY', desc: 'Award ceremony. Winners announced and prizes handed out.' }, ru: { title: 'GRAND PRIZE CEREMONY', desc: 'Награждение. Объявление победителей и вручение призов.' }, am: { title: 'GRAND PRIZE CEREMONY', desc: 'Մրցանակաբաշխություն: Հաղթողների հայտարարում և մրցանակների հանձնում:' } },
  { time: '23:00', en: { title: 'AFTERPARTY & CLOSING', desc: 'Event closing.' }, ru: { title: 'AFTERPARTY & CLOSING', desc: 'Завершение мероприятия.' }, am: { title: 'AFTERPARTY & CLOSING', desc: 'Միջոցառման ավարտ:' } },
];

export const partners = Array.from({ length: 8 }, () => ({ name: 'LOGO' }));

export const socials = [
  { label: 'IG', href: 'https://www.instagram.com/garagemastersmall/' },
  { label: 'FB', href: 'https://www.facebook.com/GarageMastersMall' },
];

export const contacts = {
  email: 'gmmplex@gmail.com',
  phones: [
    {
      tel: '+37495708993',
      display: '+374 95 708 993',
      person: {
        en: 'Raffi Unusyan — Sales Manager, Garage Mall',
        ru: 'Раффи Унусян — менеджер по продажам, Garage Mall',
        am: 'Րաֆֆի Ունուսյան — Գարաժ Մոլ, վաճառքի մենեջեր',
      },
    },
    {
      tel: '+37477697761',
      display: '+374 77 69 77 61',
      person: {
        en: 'Gohar Nazaryan — Marketing Manager, Garage Mall',
        ru: 'Гоар Назарян — менеджер по маркетингу, Garage Mall',
        am: 'Գոհար Նազարյան — Գարաժ Մոլ, մարքեթինգի մենեջեր',
      },
    },
  ],
};

export const faqList = {
  en: [
    { q: 'How do I register my car?', a: "Fill out the Participant form below with your details, vehicle info and nomination choice, then upload photos from all angles. Our team reviews every entry and contacts confirmed participants directly." },
    { q: 'Is there a participation fee?', a: 'Yes — 20,000 AMD for cars and 10,000 AMD for motorcycles. The fee is charged only after your entry is confirmed and is non-refundable.' },
    { q: 'Is entry free for visitors?', a: 'Yes, the show is free and open to the public, 15:00–23:00 at Garage Mall.' },
    { q: 'Is there parking?', a: 'Yes, free on-site parking at Garage Mall for all visitors and participants.' },
    { q: 'Can I bring my kids?', a: "Of course — it's a family-friendly event." },
    { q: 'How do I become a partner?', a: "Use the Partner tab in the registration section, or email us — we'll send the partnership deck." },
    { q: 'Can I enter more than one nomination?', a: 'A vehicle is entered in the nomination it best fits. The final nomination is confirmed by the organizers after reviewing your application.' },
    { q: 'Can I register more than one car?', a: 'Yes — submit a separate application for each car and attach the relevant photos.' },
    { q: 'What’s the registration deadline?', a: 'The deadline will be announced on the event’s official pages. We recommend applying as early as possible, as participant spots are limited.' },
    { q: 'How is the participation fee paid?', a: 'Payment details are shared only after your participation is confirmed. No payment is required before you receive official confirmation.' },
    { q: 'How are winners selected?', a: 'Entries are scored by a specialized, independent jury against the criteria set for each nomination.' },
  ],
  ru: [
    { q: 'Как записать свой автомобиль?', a: 'Заполните форму «Участник» ниже — данные, информацию об автомобиле и номинацию, затем загрузите фото со всех ракурсов. Мы рассмотрим заявку и свяжемся с подтверждёнными участниками напрямую.' },
    { q: 'Есть ли взнос за участие?', a: 'Да — 20 000 драм для автомобилей и 10 000 драм для мотоциклов. Списывается только после подтверждения участия и не возвращается.' },
    { q: 'Вход для гостей платный?', a: 'Нет, вход свободный для всех, с 15:00 до 23:00 в Garage Mall.' },
    { q: 'Есть ли парковка?', a: 'Да, бесплатная парковка на территории Garage Mall для всех гостей и участников.' },
    { q: 'Можно с детьми?', a: 'Конечно — это семейное мероприятие.' },
    { q: 'Как стать партнёром?', a: 'Используйте вкладку «Партнёр» в разделе регистрации или напишите нам — мы пришлём презентацию для партнёров.' },
    { q: 'Можно участвовать в нескольких номинациях?', a: 'Автомобиль заявляется в номинацию, которой он больше всего соответствует. Финальную номинацию подтверждают организаторы после рассмотрения заявки.' },
    { q: 'Можно зарегистрировать больше одного автомобиля?', a: 'Да — на каждый автомобиль заполните отдельную заявку и прикрепите соответствующие фото.' },
    { q: 'До какого числа можно зарегистрироваться?', a: 'Крайний срок будет опубликован на официальных страницах мероприятия. Рекомендуем подавать заявку как можно раньше — количество мест ограничено.' },
    { q: 'Как оплачивается взнос за участие?', a: 'Детали оплаты предоставляются только после подтверждения участия. До официального подтверждения оплачивать ничего не нужно.' },
    { q: 'Как выбирают победителей?', a: 'Автомобили оценивает специализированное независимое жюри по критериям, установленным для каждой номинации.' },
  ],
  am: [
    { q: 'Ինչպե՞ս կարող եմ գրանցել իմ մեքենան', a: 'Լրացրեք «Մասնակից» բաժնում տեղադրված հայտը՝ նշելով Ձեր անձնական տվյալները, մեքենայի մասին տեղեկությունները և նախընտրած անվանակարգը։ Այնուհետև կցեք մեքենայի լուսանկարները բոլոր կողմերից, ինչպես նաև սրահի լուսանկարները։ Մեր թիմը կուսումնասիրի յուրաքանչյուր հայտ և կապ կհաստատի ընտրված մասնակիցների հետ։' },
    { q: 'Մասնակցությունը վճարովի՞ է', a: 'Այո՛։ Մեքենան ներկայացնելու համար կա մասնակցության վճար։ Մասնակցության վճարը մեքենաների համար կազմում է 20 000 ՀՀ դրամ, իսկ մոտոցիկլետների համար՝ 10 000 ՀՀ դրամ։ Վճարումը կատարվում է միայն մասնակցության հաստատումից հետո և վերադարձման ենթակա չէ։' },
    { q: 'Այցելուների մուտքը վճարովի՞ է', a: 'Ո՛չ։ Այցելուների մուտքն ամբողջությամբ անվճար է։ Միջոցառումը տեղի կունենա Garage Mall-ում՝ ժամը 15:00-ից մինչև 23:00-ն։' },
    { q: 'Կա՞ կայանատեղի', a: 'Այո՛։ Garage Mall-ի տարածքում այցելուների և մասնակիցների համար հասանելի է անվճար կայանատեղի միջոցառման ընթացքում։' },
    { q: 'Կարո՞ղ եմ երեխաների հետ գալ', a: 'Իհարկե։ Tuning Show-ն նախատեսված է նաև ընտանեկան այցելությունների համար, և երեխաների համար նույնպես նախատեսված կլինեն տարբեր ժամանցային ակտիվություններ։' },
    { q: 'Ինչպե՞ս դառնալ գործընկեր', a: 'Լրացրեք գրանցման բաժնում տեղադրված «Գործընկեր» հայտը։ Մեր թիմը կապ կհաստատի Ձեզ հետ և կներկայացնի գործընկերության հնարավորությունները, ձևաչափերն ու առաջարկվող փաթեթները։' },
    { q: 'Կարո՞ղ եմ մասնակցել մի քանի անվանակարգում', a: 'Մեկ փոխադրամիջոցը ներկայացվում է այն անվանակարգում, որին առավել համապատասխանում է: Վերջնական անվանակարգը հաստատվում է կազմակերպիչների կողմից՝ հայտի ուսումնասիրությունից հետո:' },
    { q: 'Կարո՞ղ եմ գրանցել մեկից ավելի մեքենա', a: 'Այո՝ յուրաքանչյուր մեքենայի համար անհրաժեշտ է լրացնել առանձին հայտ և կցել համապատասխան լուսանկարները:' },
    { q: 'Մինչև ե՞րբ կարող եմ գրանցվել', a: 'Գրանցման վերջնաժամկետի մասին տեղեկությունը կհրապարակվի միջոցառման պաշտոնական էջերում: Խորհուրդ ենք տալիս հայտը ներկայացնել հնարավորինս շուտ, քանի որ մասնակիցների տեղերը սահմանափակ են:' },
    { q: 'Մասնակցության վճարն ինչպե՞ս է կատարվում', a: 'Վճարման մանրամասները տրամադրվում են միայն մասնակցության հաստատումից հետո: Մինչ պաշտոնական հաստատումը ստանալը որևէ վճարում կատարել անհրաժեշտ չէ:' },
    { q: 'Ինչպե՞ս են ընտրվելու հաղթողները', a: 'Մասնակիցների մեքենաները կգնահատվեն մասնագիտացված և անկախ ժյուրիի կողմից՝ յուրաքանչյուր անվանակարգի համար սահմանված չափանիշներով:' },
  ],
};

export const EVENT_TIME = new Date('2026-09-20T15:00:00+04:00').getTime();
