export const dict = {
  en: {
    nav: ['About', 'Nominations', 'Program', 'Partners', 'FAQ'],
    heroKicker: 'Sep 20, 2026 · Garage Mall, Yerevan',
    heroDate: 'September 20, 2026',
    heroSub:
      "Armenia’s loudest car culture event returns. 11 nominations, hundreds of builds, one all-out day at Garage Mall.",
    cta1: 'Register Your Car',
    cta2: 'Become a Partner',
    secAbout: 'About the show',
    aboutHead: 'One Day. Full Throttle.',
    aboutText:
      "Tuning Show brings Armenia’s car-building scene together at Garage Mall — retro, JDM, off-road, muscle, custom and more. Judged live across 11 nominations, in front of thousands of visitors. Free entry for everyone.",
    secCount: 'Countdown to show day',
    secNoms: 'Nominations',
    nomsHead: '11 Ways To Win',
    nomsSub: 'An independent jury scores every entry live on show day.',
    secProgram: 'Program',
    programHead: 'Show day, hour by hour',
    scheduleNote: 'schedule placeholder — final times TBC',
    secApply: 'Register',
    applyHead: 'Enter Your Build',
    tabParticipant: 'Participant',
    tabPartner: 'Partner',
    noticeHead: 'Before you apply',
    noticeBody:
      "Submitting this form does not guarantee confirmed participation — our team will contact confirmed entrants directly. Participation fee: 20,000 AMD for cars, 10,000 AMD for motorcycles, charged only after confirmation. Non-refundable.",
    fName: 'Full Name',
    fPhone: 'Phone Number',
    fAge: 'Age',
    fEmail: 'Email',
    optional: 'optional',
    fMake: 'Vehicle Make',
    fModel: 'Vehicle Model',
    fYear: 'Year of Manufacture',
    fPlate: 'License Plate',
    fNom: 'Choose Nomination',
    fUpload: 'Upload Photos',
    fUploadCta: 'Click or drop photos here',
    fUploadHint: 'All angles + interior, JPG or PNG',
    fCompany: 'Company Name',
    fMsg: 'Message',
    fSubmit: 'Send Application',
    thanks: 'Application received',
    thanksSub:
      "This doesn’t confirm your spot yet — we’ll contact you directly once it’s reviewed.",
    secPartners: 'Partners',
    partnersHead: 'Built with our partners',
    titleSponsor: 'Title sponsor',
    titleSponsorPlaceholder: 'YOUR LOGO',
    partnerCta: 'Become a Partner',
    secLocation: 'Location',
    locAddress: 'Garage Mall, Yerevan, Armenia',
    locParking: 'Free on-site parking for visitors',
    locHours: 'Doors 12:00 — 22:00',
    locFree: 'Free entry for all visitors',
    locDirections: 'Open in Maps',
    mapNote: 'embed Garage Mall map',
    secFaq: 'FAQ',
    faqHead: 'Good to know',
    footTag: "Armenia’s automotive tuning culture event.",
    footContact: 'Contact',
    footFollow: 'Follow',
    footPrivacy: 'Privacy Policy',
  },
  ru: {
    nav: ['О шоу', 'Номинации', 'Программа', 'Партнёры', 'Вопросы'],
    heroKicker: '20 сентября 2026 · Garage Mall, Ереван',
    heroDate: '20 сентября 2026',
    heroSub:
      'Самое громкое автособытие Армении возвращается. 11 номинаций, сотни проектов, один безудержный день в Garage Mall.',
    cta1: 'Записать авто',
    cta2: 'Стать партнёром',
    secAbout: 'О шоу',
    aboutHead: 'Один день. Полный газ.',
    aboutText:
      'Собираем автостроительное сообщество Армении в Garage Mall — ретро, JDM, off-road, масл-кар, кастом и многое другое. Живое судейство в 11 номинациях перед тысячами гостей. Вход свободный для всех.',
    secCount: 'До начала шоу',
    secNoms: 'Номинации',
    nomsHead: '11 способов победить',
    nomsSub: 'Независимое жюри оценивает каждый автомобиль вживую в день шоу.',
    secProgram: 'Программа',
    programHead: 'День шоу по часам',
    scheduleNote: 'предварительное расписание — время уточняется',
    secApply: 'Регистрация',
    applyHead: 'Заяви свой автомобиль',
    tabParticipant: 'Участник',
    tabPartner: 'Партнёр',
    noticeHead: 'Перед подачей заявки',
    noticeBody:
      'Заполнение формы не означает автоматическое подтверждение участия — наша команда свяжется с подтверждёнными участниками напрямую. Взнос за участие: 20 000 драм для автомобилей, 10 000 драм для мотоциклов, списывается только после подтверждения. Не возвращается.',
    fName: 'Имя, Фамилия',
    fPhone: 'Номер телефона',
    fAge: 'Возраст',
    fEmail: 'Email',
    optional: 'необязательно',
    fMake: 'Марка автомобиля',
    fModel: 'Модель',
    fYear: 'Год выпуска',
    fPlate: 'Гос. номер',
    fNom: 'Выберите номинацию',
    fUpload: 'Загрузите фото',
    fUploadCta: 'Нажмите или перетащите фото сюда',
    fUploadHint: 'Все ракурсы + салон, JPG или PNG',
    fCompany: 'Название компании',
    fMsg: 'Сообщение',
    fSubmit: 'Отправить заявку',
    thanks: 'Заявка принята',
    thanksSub: 'Это ещё не подтверждает участие — мы свяжемся с вами напрямую после рассмотрения.',
    secPartners: 'Партнёры',
    partnersHead: 'Сделано с партнёрами',
    titleSponsor: 'Главный спонсор',
    titleSponsorPlaceholder: 'ВАШ ЛОГОТИП',
    partnerCta: 'Стать партнёром',
    secLocation: 'Локация',
    locAddress: 'Garage Mall, Ереван, Армения',
    locParking: 'Бесплатная парковка для гостей',
    locHours: 'Двери 12:00 — 22:00',
    locFree: 'Вход свободный для всех гостей',
    locDirections: 'Открыть на карте',
    mapNote: 'здесь будет карта Garage Mall',
    secFaq: 'Вопросы',
    faqHead: 'Важно знать',
    footTag: 'Событие автотюнинговой культуры Армении.',
    footContact: 'Контакты',
    footFollow: 'Мы в соцсетях',
    footPrivacy: 'Политика конфиденциальности',
  },
  am: {
    nav: ['Մեր մասին', 'Անվանակարգեր', 'Ծրագիր', 'Գործընկերներ', 'Հարցեր'],
    heroKicker: '20 սեպտեմբերի, 2026 · Garage Mall, Երևան',
    heroDate: '20 սեպտեմբերի, 2026',
    heroSub:
      'Հայաստանի ամենաաղմկոտ ավտոմշակութային իրադարձությունը վերադառնում է: 11 անվանակարգ, հարյուրավոր նախագծեր, մեկ անմոռանալի օր Garage Mall-ում:',
    cta1: 'Գրանցել մեքենադ',
    cta2: 'Դառնալ գործընկեր',
    secAbout: 'Մեր մասին',
    aboutHead: 'Մեկ օր: Ամբողջ գազով:',
    aboutText:
      'Tuning Show-ը հավաքում է Հայաստանի ավտոկառուցման համայնքին Garage Mall-ում՝ ռետրո, JDM, օֆ-ռոդ, մասլ-կար, կաստոմ և ավելին: Ուղիղ գնահատում 11 անվանակարգերում, հազարավոր հյուրերի առջև: Մուտքն ազատ է բոլորի համար:',
    secCount: 'Հաշվարկ մինչև շոուն',
    secNoms: 'Անվանակարգեր',
    nomsHead: '11 եղանակ հաղթելու',
    nomsSub: 'Անկախ ժյուրին ուղիղ եթերում գնահատում է յուրաքանչյուր մասնակցի:',
    secProgram: 'Ծրագիր',
    programHead: 'Շոուի օրը՝ ժամ առ ժամ',
    scheduleNote: 'նախնական ժամանակացույց է — վերջնական ժամերը կճշգրտվեն',
    secApply: 'Գրանցում',
    applyHead: 'Գրանցիր քո մեքենան',
    tabParticipant: 'Մասնակից',
    tabPartner: 'Գործընկեր',
    noticeHead: 'Մինչ հայտագրվելը',
    noticeBody:
      'Հայտի լրացումը չի նշանակում ավտոմատ հաստատված մասնակցություն: Հաստատված մասնակիցների հետ կապ կհաստատեն կազմակերպիչները: Մասնակցության վճարը՝ 20,000 ՀՀ դրամ մեքենաների, 10,000 ՀՀ դրամ մոտոցիկլետների համար: Գանձվում է միայն հաստատումից հետո: Չի վերադարձվում:',
    fName: 'Անուն, Ազգանուն',
    fPhone: 'Հեռախոսահամար',
    fAge: 'Տարիք',
    fEmail: 'Email',
    optional: 'ոչ պարտադիր',
    fMake: 'Փոխադրամիջոցի մակնիշ',
    fModel: 'Փոխադրամիջոցի մոդել',
    fYear: 'Արտադրության տարեթիվ',
    fPlate: 'Պետհամարանիշ',
    fNom: 'Ընտրեք անվանակարգը',
    fUpload: 'Վերբեռնեք լուսանկարները',
    fUploadCta: 'Սեղմեք կամ քաշեք լուսանկարները այստեղ',
    fUploadHint: 'Բոլոր անկյուններից + սրահ, JPG կամ PNG',
    fCompany: 'Ընկերության անուն',
    fMsg: 'Հաղորդագրություն',
    fSubmit: 'Ուղարկել հայտը',
    thanks: 'Հայտը ստացված է',
    thanksSub: 'Դեռ մասնակցություն հաստատված չէ — մենք կապ կհաստատենք Ձեզ հետ ուղղակիորեն:',
    secPartners: 'Գործընկերներ',
    partnersHead: 'Արված գործընկերների հետ',
    titleSponsor: 'Գլխավոր հովանավոր',
    titleSponsorPlaceholder: 'ՁԵՐ ՆՇԱՆԸ',
    partnerCta: 'Դառնալ գործընկեր',
    secLocation: 'Վայր',
    locAddress: 'Garage Mall, Երևան, Հայաստան',
    locParking: 'Անվճար կայանատեղի այցելուների համար',
    locHours: 'Դռները 12:00 — 22:00',
    locFree: 'Մուտքն ազատ է բոլոր հյուրերի համար',
    locDirections: 'Բացել քարտեզում',
    mapNote: 'այստեղ կլինի Garage Mall-ի քարտեզը',
    secFaq: 'Հարցեր',
    faqHead: 'Արժե իմանալ',
    footTag: 'Հայաստանի ավտոտյունինգի մշակութային իրադարձությունը:',
    footContact: 'Կապ',
    footFollow: 'Հետևեք',
    footPrivacy: 'Գաղտնիության քաղաքականություն',
  },
};

export const countdownLabels = {
  en: ['Days', 'Hours', 'Min', 'Sec'],
  ru: ['Дни', 'Часы', 'Мин', 'Сек'],
  am: ['Օր', 'Ժամ', 'Րոպե', 'Վայրկ'],
};

export const statVals = ['100+', '11', '5,000+', '8,000 m²'];

export const statLabels = {
  en: ['Builds & projects', 'Nominations', 'Expected visitors', 'Exhibition area'],
  ru: ['Проектов', 'Номинаций', 'Посетителей', 'Площадь'],
  am: ['Նախագծեր', 'Անվանակարգեր', 'Այցելուներ', 'Տարածք'],
};

export const nominations = [
  { en: 'Best Retro Car (up to 1959)', ru: 'Лучший ретроавтомобиль (до 1959 г.)', am: 'Լավագույն ռետրո մեքենա (մինչև 1959 թ.)' },
  { en: 'Best Retro Car (1960–1980)', ru: 'Лучший ретроавтомобиль (1960–1980)', am: 'Լավագույն ռետրո մեքենա (1960–1980 թթ.)' },
  { en: 'Best Historic Japan / JDM', ru: 'Лучший Historic Japan / JDM', am: 'Լավագույն Historic Japan / JDM' },
  { en: 'Best Off-Road (Camping Build)', ru: 'Лучший off-road (Camping Build)', am: 'Լավագույն օֆ-ռոդ մեքենա (Camping Build)' },
  { en: 'Best Off-Road (Sport Build)', ru: 'Лучший off-road (Sport Build)', am: 'Լավագույն օֆ-ռոդ մեքենա (Sport Build)' },
  { en: 'Best Off-Road (Best Tuned)', ru: 'Лучший off-road (Best Tuned Off-Road)', am: 'Լավագույն օֆ-ռոդ մեքենա (Best Tuned Off-Road)' },
  { en: 'Best Exterior', ru: 'Лучший экстерьер', am: 'Լավագույն արտաքին տեսք' },
  { en: 'Best Motorcycle (Chopper / Cruiser / Sport)', ru: 'Лучший мотоцикл (Chopper / Cruiser / Sport Bike)', am: 'Լավագույն մոտոցիկլետ (Chopper / Cruiser / Sport Bike)' },
  { en: 'Best Muscle Car', ru: 'Лучший Muscle Car', am: 'Լավագույն Muscle Car' },
  { en: 'Best Custom Build', ru: 'Лучший кастом-проект (Custom Build)', am: 'Լավագույն ինքնաշեն նախագիծ (Custom Build)' },
  { en: 'Best Sports Car', ru: 'Лучший спорткар', am: 'Լավագույն սպորտային մեքենա' },
];

export const schedule = [
  { time: '12:00', en: { title: 'Gates open', desc: 'Doors, registration & exhibitor load-in complete.' }, ru: { title: 'Открытие ворот', desc: 'Вход, регистрация и размещение участников.' }, am: { title: 'Դռների բացում', desc: 'Մուտք, գրանցում և մասնակիցների տեղաբաշխում:' } },
  { time: '13:00', en: { title: 'Official opening', desc: 'Host welcome and partner showcase.' }, ru: { title: 'Официальное открытие', desc: 'Приветствие и презентация партнёров.' }, am: { title: 'Պաշտոնական բացում', desc: 'Ողջույնի խոսք և գործընկերների ներկայացում:' } },
  { time: '14:30', en: { title: 'Dyno runs', desc: 'Live power pulls on the rolling road.' }, ru: { title: 'Заезды на дино', desc: 'Замеры мощности вживую.' }, am: { title: 'Դինամոմետր փորձարկումներ', desc: 'Հզորության ցուցադրում ուղիղ եթերում:' } },
  { time: '16:00', en: { title: 'Best-in-show walk', desc: 'Jury tours every category on the floor.' }, ru: { title: 'Обход жюри', desc: 'Оценка всех 11 номинаций на площадке.' }, am: { title: 'Ժյուրիի շրջայց', desc: 'Գնահատում բոլոր 11 անվանակարգերում:' } },
  { time: '20:00', en: { title: 'Awards ceremony', desc: 'Winners announced across all 11 nominations.' }, ru: { title: 'Награждение', desc: 'Объявление победителей во всех 11 номинациях.' }, am: { title: 'Մրցանակաբաշխություն', desc: 'Հաղթողների հայտարարում բոլոր 11 անվանակարգերում:' } },
];

export const partners = Array.from({ length: 8 }, () => ({ name: 'LOGO' }));
export const socials = ['IG', 'FB', 'TG'];

export const faqList = {
  en: [
    { q: 'How do I register my car?', a: "Fill out the Participant form below with your details, vehicle info and nomination choice, then upload photos from all angles. Our team reviews every entry and contacts confirmed participants directly." },
    { q: 'Is there a participation fee?', a: 'Yes — 20,000 AMD for cars and 10,000 AMD for motorcycles. The fee is charged only after your entry is confirmed and is non-refundable.' },
    { q: 'Is entry free for visitors?', a: 'Yes, the show is free and open to the public, 12:00–22:00 at Garage Mall.' },
    { q: 'Is there parking?', a: 'Yes, free on-site parking at Garage Mall for all visitors and participants.' },
    { q: 'Can I bring my kids?', a: "Of course — it's a family-friendly event." },
    { q: 'How do I become a partner?', a: "Use the Partner tab in the registration section, or email us — we'll send the partnership deck." },
  ],
  ru: [
    { q: 'Как записать свой автомобиль?', a: 'Заполните форму «Участник» ниже — данные, информацию об автомобиле и номинацию, затем загрузите фото со всех ракурсов. Мы рассмотрим заявку и свяжемся с подтверждёнными участниками напрямую.' },
    { q: 'Есть ли взнос за участие?', a: 'Да — 20 000 драм для автомобилей и 10 000 драм для мотоциклов. Списывается только после подтверждения участия и не возвращается.' },
    { q: 'Вход для гостей платный?', a: 'Нет, вход свободный для всех, с 12:00 до 22:00 в Garage Mall.' },
    { q: 'Есть ли парковка?', a: 'Да, бесплатная парковка на территории Garage Mall для всех гостей и участников.' },
    { q: 'Можно с детьми?', a: 'Конечно — это семейное мероприятие.' },
    { q: 'Как стать партнёром?', a: 'Используйте вкладку «Партнёр» в разделе регистрации или напишите нам — мы пришлём презентацию для партнёров.' },
  ],
  am: [
    { q: 'Ինչպե՞ս գրանցել իմ մեքենան', a: 'Լրացրեք ստորև «Մասնակից» ձևը՝ Ձեր տվյալները, մեքենայի մասին տեղեկությունը և անվանակարգը, ապա վերբեռնեք լուսանկարներ բոլոր անկյուններից: Մեր թիմը կդիտարկի հայտը և կապ կհաստատի հաստատված մասնակիցների հետ:' },
    { q: 'Մասնակցության համար վճար կա՞', a: 'Այո՝ 20,000 ՀՀ դրամ մեքենաների և 10,000 ՀՀ դրամ մոտոցիկլետների համար: Գանձվում է միայն հաստատումից հետո և չի վերադարձվում:' },
    { q: 'Հանդիսատեսների մուտքն անվճա՞ր է', a: 'Այո, մուտքն ազատ է բոլորի համար, 12:00–22:00, Garage Mall-ում:' },
    { q: 'Կա՞ արդյոք կայանատեղի', a: 'Այո, Garage Mall-ն առաջարկում է անվճար կայանատեղի բոլոր այցելուների և մասնակիցների համար:' },
    { q: 'Կարո՞ղ եմ երեխաների հետ գալ', a: 'Անպայման — սա ընտանեկան միջոցառում է:' },
    { q: 'Ինչպե՞ս դառնալ գործընկեր', a: 'Օգտագործեք «Գործընկեր» սեկցիան կամ գրեք մեզ. կուղարկենք համագործակցության փաթեթը:' },
  ],
};

export const EVENT_TIME = new Date('2026-09-20T12:00:00+04:00').getTime();
